/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ru.ankoks;

import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.UIManager;
import javax.swing.border.MatteBorder;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author AntonK
 */
public class StatisticsFrame extends javax.swing.JFrame {

    /**
     * Creates new form StatisticsFrame
     */
    public StatisticsFrame() {
        initComponents();
    }
    
    private static int rowNum;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTablePanel = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableAll = new javax.swing.JTable();
        jLabelLastNum = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Casino statistic");
        setBackground(new java.awt.Color(0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(520, 1000));
        setSize(new java.awt.Dimension(520, 1000));

        jTablePanel.setBorder(javax.swing.BorderFactory.createTitledBorder("table"));
        getContentPane().setBackground(Color.BLACK);
        jTablePanel.setBackground(Color.BLACK);

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jTextField1.setBackground(Color.BLACK);
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTableAll.setBackground(new java.awt.Color(0, 0, 0));
        jTableAll.setFont(new java.awt.Font("Tahoma", 0, 50)); // NOI18N
        jTableAll.setGridColor(Color.WHITE);
        jTableAll.setForeground(new java.awt.Color(255, 0, 0));
        jTableAll.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Black", "Zero", "Red"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTableAll.setAlignmentX(5.0F);
        jTableAll.setAlignmentY(5.0F);
        jTableAll.setRowHeight(50);
        TableColumn tm1 = jTableAll.getColumnModel().getColumn(0);
        TableColumn tm2 = jTableAll.getColumnModel().getColumn(1);
        TableColumn tm3 = jTableAll.getColumnModel().getColumn(2);
        tm1.setCellRenderer(new ColorColumnRenderer(Color.BLACK, Color.RED));
        tm1.setHeaderRenderer(new HeaderRenderer(Color.BLACK, Color.RED));
        tm2.setCellRenderer(new ColorColumnRenderer(Color.BLACK, Color.GREEN));
        tm2.setHeaderRenderer(new HeaderRenderer(Color.BLACK, Color.GREEN));
        tm3.setCellRenderer(new ColorColumnRenderer(Color.BLACK, Color.ORANGE));
        tm3.setHeaderRenderer(new HeaderRenderer(Color.BLACK, Color.ORANGE));
        jScrollPane4.setViewportView(jTableAll);

        jLabelLastNum.setFont(new java.awt.Font("Tahoma", 0, 50)); // NOI18N
        jLabelLastNum.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jTablePanelLayout = new javax.swing.GroupLayout(jTablePanel);
        jTablePanel.setLayout(jTablePanelLayout);
        jTablePanelLayout.setHorizontalGroup(
            jTablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jTablePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jTablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jTablePanelLayout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelLastNum, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jTablePanelLayout.setVerticalGroup(
            jTablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jTablePanelLayout.createSequentialGroup()
                .addGroup(jTablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelLastNum, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 829, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTablePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTablePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        insertRow();
        
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void insertRow() {
        /*DefaultTableModel modelBlack = (DefaultTableModel) jTableBlack.getModel();
        DefaultTableModel modelZero = (DefaultTableModel) jTableZero.getModel();
        DefaultTableModel modelRed = (DefaultTableModel) jTableRed.getModel();*/
        
        DefaultTableModel modelAll = (DefaultTableModel) jTableAll.getModel();

        String number = jTextField1.getText();
        try {
            if (number != null && Integer.parseInt(number) >= 0 && Integer.parseInt(number) < 37) {
                jLabelLastNum.setText(jTextField1.getText());
                if (number.equals("0")) {
                    /*modelBlack.insertRow(0, new Object[]{null});
                    modelZero.insertRow(0, new Object[]{number});
                    modelRed.insertRow(0, new Object[]{null});*/
                    
                    modelAll.insertRow(0, new Object[]{null, number, null});
                } else if (Integer.parseInt(number) % 2 == 0) {
                    /*modelBlack.insertRow(0, new Object[]{number});
                    modelZero.insertRow(0, new Object[]{null});
                    modelRed.insertRow(0, new Object[]{null});*/
                    
                    modelAll.insertRow(0, new Object[]{number, null, null});
                } else {
                    /*modelBlack.insertRow(0, new Object[]{null});
                    modelZero.insertRow(0, new Object[]{null});
                    modelRed.insertRow(0, new Object[]{number});*/
                    
                    modelAll.insertRow(0, new Object[]{null, null, number});
                }
                if (rowNum == 15) {
                    modelAll.removeRow(rowNum);
                    rowNum--;
                } rowNum++;
                
            }
        } catch (NumberFormatException nfe) {
            //empty body
        } finally {
            jTextField1.setText(null);
        }
    }

    /*private void insertByButton(Boolean trueIfOdd, String value) {
        DefaultTableModel model = (DefaultTableModel) jTableBlack.getModel();
        if (trueIfOdd == null) {
            model.insertRow(0, new Object[]{null, value, null});
        } else if (trueIfOdd) {
            model.insertRow(0, new Object[]{value, null, null});
        } else {
            model.insertRow(0, new Object[]{null, null, value});
        }
    }*/

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StatisticsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StatisticsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StatisticsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StatisticsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StatisticsFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelLastNum;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTableAll;
    private javax.swing.JPanel jTablePanel;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
